//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHTHONGKE
    {
        public string MATK { get; set; }
        public string MANV { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
